version: '3.8'

services:
  database:
    image: percona/percona-server:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: good
      MYSQL_DATABASE: good
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '3315:3306'
  php:
    build:
      context: ./docker/php
    ports:
      - '9005:9000'
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8084:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database